name: receitas

services:
  front-end:
    container_name: front-end
    image: ghcr.io/ryanrpj/frontend-plataforma-de-receitas:latest
    ports:
      - 5050:4173
    depends_on:
      - back-end
    restart: always

  back-end:
    container_name: back-end
    image: ghcr.io/ryanrpj/backend-plataforma-de-receitas:latest
    restart: always
    ports:
      - 9823:9823
    volumes:
      - your-courses:/courses:ro